services:
  database:
    container_name: boid-mysql
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: test
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: boid
      MYSQL_USER: boid
      MYSQL_PASSWORD: boid
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    networks:
      - boid
  backend:
    container_name: boid-backend
    image: node:20
    working_dir: /app
    # build:
    #   context: .
    #   dockerfile: ./docker/backend/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: ./bin/backend_dev.sh
    depends_on:
      - database
    ports:
      - 8080:3000
      - 8081:8081
    networks:
        - boid
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  boid:

volumes:
  db-data:
